name: base_widget_flutter
description: A lightweight Flutter package that provides a reusable BaseWidget wrapper around Scaffold for consistent UI structure, simplifying screen development with optional AppBar support.
version: 1.0.4
homepage: https://github.com/rutvikpipariya/base_widget_flutter

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  platforms:
    android:
    ios: